export const SET_TARGET_TAB = 'SET_TARGET_TAB';
export const SAVE_INGREDIENTS = 'SAVE_INGREDIENTS';
export const SET_ACTIVE = 'SET_ACTIVE';
export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const SET_BUNS = 'SET_BUN';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const SORT_INGREDIENTS = 'SORT_INGREDIENTS';
export const SET_AMOUNT = 'SET_AMOUNT';
