export const SET_TARGET_TAB = 'SET_TARGET_TAB';
export const SAVE_INGREDIENTS = 'SAVE_INGREDIENTS';
export const SET_ACTIVE = 'SET_ACTIVE';
export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const SET_BUNS = 'SET_BUN';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const SORT_INGREDIENTS = 'SORT_INGREDIENTS';
export const SET_AMOUNT = 'SET_AMOUNT';
export const SET_CLEAR_CONSTRUCTOR = 'SET_CLEAR_CONSTRUCTOR';

export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const LOGOUT_STATUS = 'LOGOUT_STATUS';

export const GET_USER_AUTH_REQUEST = 'GET_USER_AUTH_REQUEST';
export const GET_USER_AUTH_SUCCESS = 'GET_USER_AUTH_SUCCESS';
export const GET_USER_AUTH_FAILED = 'GET_USER_AUTH_FAILED';

export const EDIT_USER_AUTH_REQUEST = 'EDIT_USER_AUTH_REQUEST';
export const EDIT_USER_AUTH_SUCCESS = 'EDIT_USER_AUTH_SUCCESS';
export const EDIT_USER_AUTH_FAILED = 'EDIT_USER_AUTH_FAILED';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const CLEAR_STATE = 'CLEAR_STATE';
